---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-events
  labels:
    app: kubernetes-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-events
subjects:
- kind: ServiceAccount
  name: kubernetes-events
  namespace: opentelemetry-operator
