---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sattributes-processor-kubernetes-events
roleRef:
  kind: ClusterRole
  name: k8sattributes-processor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubernetes-events
  namespace: opentelemetry-operator
