---
name: Build Product Image
description: This action builds a product Docker image with a specific version
inputs:
  product-name:
    description: The name of the product to build via bake (directory name)
    required: true
  product-version:
    description: The version of the product to build via bake
    required: true
  image-tools-version:
    description: The Stackable image-tools version
    default: 0.0.14
  bake-config-file:
    description: Path to the bake config file, defaults to `./conf.py`
    default: ./conf.py
  sdp-version:
    description: |
      Stackable Data Platform version (eg: `24.7.0`)
    default: 0.0.0-dev
  extra-tag-data:
    description: |
      Extra data to include in the final image manifest tag (eg: `pr321`)
outputs:
  image-manifest-tag:
    description: |
      Human-readable tag (usually the version) with architecture information,
      for example: `3.4.1-stackable0.0.0-dev-amd64`
    value: ${{ steps.image_info.outputs.IMAGE_MANIFEST_TAG }}
  suggested-image-index-manifest-tag:
    description: |
      Human-readable tag (usually the version) without architecture information,
      for example: `3.4.1-stackable0.0.0-dev`
    value: ${{ steps.image_info.outputs.IMAGE_INDEX_MANIFEST_TAG }}
runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      # NOTE (@Techassi): Why do we install python via apt and not the setup-python action?
    - name: Setup Python
      shell: bash
      run: |
        set -euo pipefail
        sudo apt update
        sudo apt install -y python3

    - name: Install image-tools-stackabletech
      shell: bash
      run: pip install image-tools-stackabletech==${{ inputs.image-tools-version }}

    - name: Building ${{ inputs.product-name }} Container Image using bake
      env:
        BAKE_PRODUCT_VERSION: ${{ inputs.product-version }}
        BAKE_CONFIG_FILE: ${{ inputs.bake-config-file }}
        IMAGE_REPOSITORY: ${{ inputs.product-name }}
        EXTRA_TAG_DATA: ${{ inputs.extra-tag-data }}
        SDP_VERSION: ${{ inputs.sdp-version }}
      shell: bash
      run: |
        set -euo pipefail
        IMAGE_ARCH=$("$GITHUB_ACTION_PATH/../.scripts/get_architecture.sh")

        # Will be either:
        # - 3.9.2-stackable0.0.0-dev-arm64 or
        # - 3.9.2-stackable0.0.0-dev-pr321-arm64
        IMAGE_INDEX_MANIFEST_TAG="${SDP_VERSION}${EXTRA_TAG_DATA:+-$EXTRA_TAG_DATA}-${IMAGE_ARCH}"
        echo "IMAGE_INDEX_MANIFEST_TAG=$IMAGE_INDEX_MANIFEST_TAG" | tee -a "$GITHUB_ENV"

        # Validate that final tag is valid according to
        # https://github.com/distribution/reference/blob/8c942b0459dfdcc5b6685581dd0a5a470f615bff/regexp.go#L68
        if ! echo "$IMAGE_INDEX_MANIFEST_TAG" | grep --perl-regexp --quiet '^[\w][\w.-]{1,127}$'; then
          >&2 echo "Encountered invalid image manifest tag: $IMAGE_INDEX_MANIFEST_TAG"
          exit 1
        fi

        echo "::group::bake"
        bake \
          --product "$IMAGE_REPOSITORY=$BAKE_PRODUCT_VERSION" \
          --image-version "$IMAGE_INDEX_MANIFEST_TAG" \
          --architecture "linux/${IMAGE_ARCH}" \
          --export-tags-file bake-target-tags \
          --configuration "$BAKE_CONFIG_FILE"
        echo "::endgroup::"

    - name: Re-tag Image (Temporary)
      shell: bash
      run: |
        set -euo pipefail

        # Extract the image uri and replace 'oci.stackable.tech/sdp'
        # with 'localhost' until bake does the right thing
        OLD_IMAGE_URI="$(< bake-target-tags)"

        # Replace the image uri in the bake file
        sed -i -e 's/oci\.stackable\.tech\/sdp/localhost/' bake-target-tags

        # Finally, re-tag image
        docker tag "$OLD_IMAGE_URI" "$(< bake-target-tags)"

    - name: Extract Environment Variables
      id: image_info
      shell: bash
      run: |
        set -euo pipefail
        echo "bake-target-tags: "$(< bake-target-tags)

        # Extract the image manifest tag from the bake-target-tags file
        IMAGE_MANIFEST_TAG=$(cut -d : -f 2 < bake-target-tags)
        [[ -n "$IMAGE_MANIFEST_TAG" ]]
        [[ -n "$IMAGE_INDEX_MANIFEST_TAG" ]]

        # Add the contents of the env variables to the GitHub output, so that it
        # can be used as action outputs
        echo "IMAGE_MANIFEST_TAG=$IMAGE_MANIFEST_TAG" | tee -a "$GITHUB_OUTPUT"
        echo "IMAGE_INDEX_MANIFEST_TAG=$IMAGE_INDEX_MANIFEST_TAG" | tee -a "$GITHUB_OUTPUT"
