---
name: Free Disk Space
description: This action frees up disk space on a runner.
inputs:
  product-name:
    description: The name of the product to build via bake (directory name)
    required: true
  config-file:
    description: Path the the config file used to generate the shard indices
    default: ./conf.py
outputs:
  versions:
    description: A list of product versions
    value: ${{ steps.generate_shards.outputs.VERSIONS }}
runs:
  using: composite
  steps:
    - name: Free Disk Space (Parallel)
      shell: bash
      run: |
        # WARNING: `set -e` is not set as we purposefully want this to run optimistically.

        function cleanup_android() {
          (
            sudo rm -rf /usr/local/lib/android || true
          )>/dev/null
        }

        function cleanup_apt() {
          (
            sudo apt-get remove --fix-missing -y '^aspnetcore-.*' \
              '^dotnet-.*' \
              '^llvm-.*' \
              'php.*' \
              '^mongodb-.*' \
              '^mysql-.*' \
              azure-cli \
              google-chrome-stable \
              firefox \
              powershell \
              mono-devel \
              libgl1-mesa-dri \
              google-cloud-sdk \
              google-cloud-cli || true
            sudo apt-get autoremove -y
            sudo apt-get clean
          )>/dev/null
        }

        function cleanup_dotnet() {
          (
            sudo rm -rf /usr/share/dotnet || true
          )>/dev/null
        }

        function cleanup_haskell() {
          (
            sudo rm -rf /opt/ghc || true
            sudo rm -rf /usr/local/.ghcup || true
          )>/dev/null
        }

        function cleanup_docker() {
          (
            sudo docker image prune --all --force || true
          )>/dev/null
        }

        function cleanup_agenttools() {
          (
            sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          )>/dev/null
        }

        function disable_swap() {
          (
            sudo swapoff -a || true
            sudo rm -f /mnt/swapfile || true
            free -h
          )>/dev/null
        }

        echo "::group::Disk usage before"
        df -h /
        echo "::endgroup::"

        echo "::group::Parallel cleanup"

        # NOTE: The `\` infront of the time command prevents the bash built-in command.
        \time --format 'Removed Android libraries (%es)' cleanup_android &
        \time --format 'Removed apt packages (%es)' cleanup_apt &
        \time --format 'Removed dotnet packages (%es)' cleanup_dotnet &
        \time --format 'Removed haskell (%es)' cleanup_haskell &
        \time --format 'Pruned docker images (%es)' cleanup_docker &
        \time --format 'Disabled swap (%es)' disable_swap &

        # This might remove tools that are actually needed, if set to "true" but
        # frees about 6 GB.
        # \time --format 'Removed agent tools (%es)' cleanup_agenttools &

        echo "Waiting for cleanup tasks"
        wait
        echo "::endgroup::"

        echo "::group::Disk usage after"
        df -h /
        echo "::endgroup::"
