---
namePrefix: replicated-

resources:
- ../../bases/opentelemetry-collectors

patches:
# Update all collectors to set the exporter endpoints and any other common overrides.
- target:
    group: opentelemetry.io
    version: v1beta1
    kind: OpenTelemetryCollector
  patch: |-
    - op: add
      path: /spec/config/exporters/otlp
      value:
        endpoint: otel-logs-source.nick.stackable.build:443
        # tls:
        #   insecure: true
    - op: add
      path: /spec/config/service/pipelines/logs/exporters/-
      value: otlp
    - op: add
      path: /spec/envFrom/-
      value:
        configMapRef:
          name: integration-test-info
    - op: add
      path: /spec/config/processors/resource/attributes/-
      value:
        action: upsert
        key: k8s.cluster.name
        value: ${env:KUBERNETES_CLUSTER_NAME}
    - op: add
      path: /spec/config/processors/resource/attributes/-
      value:
        action: upsert
        key: k8s.cluster.distribution
        value: ${env:KUBERNETES_DISTRIBUTION}
    - op: add
      path: /spec/config/processors/resource/attributes/-
      value:
        action: upsert
        key: k8s.cluster.version
        value: ${env:KUBERNETES_VERSION}
    - op: add
      path: /spec/config/processors/resource/attributes/-
      value:
        action: upsert
        key: github.actions.triggered_by
        value: ${env:TRIGGERED_BY}

# Specifically override config for the kubernetes-events collector.
- target:
    group: opentelemetry.io
    version: v1beta1
    kind: OpenTelemetryCollector
    name: kubernetes-events
  patch: |-
    # OpenSearch Metrics collector is not yet available
    - op: remove
      path: /spec/config/service/pipelines/metrics
    # - op: add
    # - op: add
    #   path: /spec/config/service/pipelines/metrics/exporters/-
    #   value: otlphttp

configMapGenerator:
# These get used by the attributes processor in each collector
- name: integration-test-info
  namespace: opentelemetry-operator
  envs:
  # KUBERNETES_CLUSTER_NAME
  # KUBERNETES_DISTRIBUTION
  # KUBERNETES_VERSION
  # TRIGGERED_BY
  - integration-test-info.env
