---
name: detect-changes
description: Detect changed files by providing a list of glob patterns
inputs:
  patterns:
    description: A list of glob patterns to detect changes in. Defaults to ['*'].
    default: "['*']"
outputs:
  detected:
    description: Returns if any changed files were matched by the provided glob patterns.
    value: ${{ steps.check.outputs.DETECTED }}
runs:
  using: composite
  steps:
    - name: Check for changed files
      id: check
      env:
        PATTERNS: ${{ inputs.patterns }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
      shell: bash
      run: |
        set -euo pipefail

        if [ "$GITHUB_EVENT_NAME" != 'pull_request' ]; then
          # This is a short-circuit for when not run on a PR.
          # It saves having to make the job conditions even more complicated.
          echo "Not running on a PR. Hard-coding result:"
          echo "DETECTED=true" | tee -a "$GITHUB_OUTPUT"
          exit 0
        fi

        # This is cursed... we use `.[] | .` to remove quotes and any yaml formatting.
        readarray -t GLOBS < <(echo -n "$PATTERNS" | yq '.[] | .')

        DETECTED="false"
        for GLOB in "${GLOBS[@]}"; do
            if ! git diff --exit-code --name-only "${BASE_SHA}.." -- "$GLOB"; then
              # When git diff exist with an error, that means there was a diff
              # for the glob.
              DETECTED="true"
            fi
        done

        echo "DETECTED=$DETECTED" | tee -a "$GITHUB_OUTPUT"
