---
# See also namespace setting for the helm chart below. Helm needs to calculate the namespace for the certificate subject.
namespace: opentelemetry-operator

resources:
- namespace.yml

helmCharts:
- name: opentelemetry-operator
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  # Find the latest release here: https://github.com/open-telemetry/opentelemetry-helm-charts/releases
  version: 0.92.2
  releaseName: opentelemetry-operator
  includeCRDs: true
  skipTests: true
  namespace: opentelemetry-operator
  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/opentelemetry-operator-0.92.2/charts/opentelemetry-operator/values.yaml
  valuesInline:
    manager:
      collectorImage:
        # Find the latest release here: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/
        # See which plugins the opentelemetry-collector-k8s image contains here:
        # https://github.com/open-telemetry/opentelemetry-collector-releases/blob/main/distributions/otelcol-k8s/manifest.yaml
        repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
        tag: 0.131.1 # Often the chart has old values for the collector image
    admissionWebhooks:
      certManager:
        enabled: false
      autoGenerateCert:
        enabled: true
