---
name: Build Product Image
description: This action builds a product Docker image with a specific version
inputs:
  image-name:
    description: |
      The local name of the built image, for example: `kafka` or
      `csi-provisioner`
    required: true
  image-index-manifest-tag:
    description: |
      Human-readable tag (usually the version) without architecture information,
      for example: `3.4.1-stackable0.0.0-dev`
  container-file:
    description: Path to Containerfile (or Dockefile)
    default: Dockerfile
  build-context:
    description: Path to the build-context
    default: .
  # TODO (@NickLarsenNZ): Allow optional buildx cache
  # build-cache-username:
  #   description: Build cache username
  #   default: github
  # build-cache-password:
  #   description: Build cache password
  #   required: true
outputs:
  image-repository-uri:
    description: |
      The locally tagged name of the image, for example: `localhost/kafka`
    value: ${{ steps.build-image.outputs.IMAGE_REPOSITORY_URI }}
  image-manifest-tag:
    description: |
      Human-readable tag (usually the version) with architecture information,
      for example: `3.4.1-stackable0.0.0-dev-amd64`
    value: ${{ steps.build-image.outputs.IMAGE_MANIFEST_TAG }}
  image-manifest-uri:
    description: |
      The full image manifest uri, for example:
      localhost/kafka:3.4.1-stackable0.0.0-dev-amd64
    value: ${{ steps.build-image.outputs.IMAGE_MANIFEST_URI }}
runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

    # TODO (@NickLarsenNZ): Allow optional buildx cache
    #   # Needed if you pass the --cache argument to the bake command below
    # - name: Login to the docker build cache registry
    #   uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
    #   with:
    #     registry: build-repo.stackable.tech:8083
    #     username: ${{ inputs.build-cache-username }}
    #     password: ${{ inputs.build-cache-password }}

    - name: Build ${{ inputs.image-name }}:${{ inputs.image-index-manifest-tag }}
      id: build-image
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_INDEX_MANIFEST_TAG: ${{ inputs.image-index-manifest-tag }}
        CONTAINER_FILE: ${{ inputs.container-file }}
        BUILD_CONTEXT: ${{ inputs.build-context }}
      shell: bash
      run: |
        set -euo pipefail

        IMAGE_ARCH=$("$GITHUB_ACTION_PATH/../.scripts/get_architecture.sh")
        echo "IMAGE_ARCH=${IMAGE_ARCH}" | tee -a "$GITHUB_ENV"

        IMAGE_MANIFEST_TAG="${IMAGE_INDEX_MANIFEST_TAG}-${IMAGE_ARCH}"
        echo "IMAGE_MANIFEST_TAG=${IMAGE_MANIFEST_TAG}" | tee -a "$GITHUB_OUTPUT"

        IMAGE_REPOSITORY_URI="localhost/${IMAGE_NAME}"
        echo "IMAGE_REPOSITORY_URI=${IMAGE_REPOSITORY_URI}" | tee -a "$GITHUB_OUTPUT"

        IMAGE_MANIFEST_URI="${IMAGE_REPOSITORY_URI}:${IMAGE_MANIFEST_TAG}"
        echo "IMAGE_MANIFEST_URI=${IMAGE_MANIFEST_URI}" | tee -a "$GITHUB_OUTPUT"

        echo "::group::docker buildx build"
        # TODO (@NickLarsenNZ): Allow optional buildx cache
        docker buildx build \
        --file "${CONTAINER_FILE}" \
        --platform "linux/${IMAGE_ARCH}" \
        --tag "${IMAGE_MANIFEST_URI}" \
        --load \
        "${BUILD_CONTEXT}"
        echo "::endgroup::"

        echo "::group::docker images"
        docker images
        echo "::endgroup::"
