---
name: Setup Kubernetes Tools
description: This action sets up Kubernetes tools
inputs:
  kubectl-version:
    description: The version of kubectl
  kuttl-version:
    description: The version of kubectl-kuttl
  helm-version:
    description: The version of helm
runs:
  using: composite
  steps:
    # We technically don't need to install kubectl, kind or helm because it is already part of the installed
    # tools of the runner image, but we at least install kubectl and helm explicitly, to be able to pin the versions.
    # See https://github.com/actions/runner-images/blob/main/images/ubuntu/scripts/build/install-kubernetes-tools.sh
    - name: Install kubectl
      if: inputs.kubectl-version
      env:
        KUBECTL_VERSION: ${{ inputs.kubectl-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_kubectl.sh"

    - name: Install kubectl-kuttl
      if: inputs.kuttl-version
      env:
        KUTTL_VERSION: ${{ inputs.kuttl-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_kubectl_kuttl.sh"

    - name: Install Helm
      if: inputs.helm-version
      env:
        HELM_VERSION: ${{ inputs.helm-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_helm.sh"
