---
name: Generate Shards
description: This action builds list of shard indices for use in Github Actions Matrices
inputs:
  product-name:
    description: The name of the product to build via bake (directory name)
    required: true
  boil-version:
    description: The boil version
    default: latest
outputs:
  versions:
    description: A list of product versions
    value: ${{ steps.generate_shards.outputs.VERSIONS }}
runs:
  using: composite
  steps:
    - uses: stackabletech/actions/setup-tools@refactor/build-product-image-use-boil # TODO: Replace with latest released version
      with:
        boil-version: ${{ inputs.boil-version }}

    - name: Generate Shards
      id: generate_shards
      env:
        PRODUCT_NAME: ${{ inputs.product-name }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        VERSIONS=$(boil show images "$PRODUCT_NAME" | jq --compact-output ".$PRODUCT_NAME")
        echo "VERSIONS=$VERSIONS" | tee -a "$GITHUB_OUTPUT"

    - name: Print Shards
      env:
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        echo versions=${{ steps.generate_shards.outputs.VERSIONS }}
