---
name: Generate Shards
description: This action builds list of shard indices for use in Github Actions Matrices
inputs:
  product-name:
    description: The name of the product to build via bake (directory name)
    required: true
  boil-version:
    description: The boil version
    default: latest
outputs:
  versions:
    description: A list of product versions
    value: ${{ steps.generate_shards.outputs.VERSIONS }}
runs:
  using: composite
  steps:
    - name: Setup boil (${{ inputs.boil-version }})
      env:
        BOIL_VERSION: ${{ inputs.boil-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_boil.sh"

    - name: Generate Shards
      id: generate_shards
      env:
        PRODUCT_NAME: ${{ inputs.product-name }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        VERSIONS=$(boil show images "$PRODUCT_NAME" | jq --compact-output --arg product_name "$PRODUCT_NAME" '.[$product_name]')
        echo "VERSIONS=$VERSIONS" | tee -a "$GITHUB_OUTPUT"

    - name: Print Shards
      env:
        GITHUB_DEBUG: ${{ runner.debug }}
        VERSIONS: ${{ steps.generate_shards.outputs.VERSIONS }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        echo "versions=$VERSIONS"
