---
name: Send Notification via Slack
description: ""
inputs:
  channel-id:
    description: The channel to sent the message to
    default: C07UG6JH44F # notifications-container-images
  build-result:
    description: The result of the build job
  publish-manifests-result:
    description: The result of the publish manifests job
  slack-token:
    description: The Slack token
runs:
  using: composite
  steps:
    - name: Retrieve Slack Thread ID
      id: retrieve-slack-thread-id
      continue-on-error: true
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
      with:
        name: slack-thread-id-${{ github.run_id }}

    - name: Extract Slack Thread ID into Environment Variable
      env:
        RETRIEVE_SLACK_THREAD_ID_RESULT: ${{ steps.retrieve-slack-thread-id.result }}
      shell: bash
      run: |
        if [ "$RETRIEVE_SLACK_THREAD_ID_RESULT" = "success" ]; then
          echo "SLACK_THREAD_ID=$(cat slack-thread-id)" | tee -a "$GITHUB_ENV"
        else
          echo "SLACK_THREAD_ID=none" | tee -a "$GITHUB_ENV"
        fi

    - name: Format message
      env:
        PUBLISH_MANIFESTS_RESULT: ${{ inputs.publish-manifests-result }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        GITHUB_WORKFLOW: ${{ github.workflow  }}
        BUILD_RESULT: ${{ inputs.build-result }}
      shell: bash
      run: |
        if [ "$PUBLISH_MANIFESTS_RESULT" = "failure" ] || [ "$BUILD_RESULT" = "failure" ]; then
          MESSAGE_VERB=failed
          MESSAGE_COLOR=aa0000
        else
          MESSAGE_VERB=succeeded
          MESSAGE_COLOR=10c400

        echo "MESSAGE_TEXT=*$GITHUB_WORKFLOW* $MESSAGE_VERB (attempt $GITHUB_RUN_ATTEMPT)" | tee -a "$GITHUB_ENV"
        echo "MESSAGE_COLOR=$MESSAGE_COLOR" | tee -a "$GITHUB_ENV"
        echo "MESSAGE_VERB=$MESSAGE_VERB" | tee -a "$GITHUB_ENV"

    - name: Send Notification
      id: send-notification
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # 2.1.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-token }}
        payload: |
          channel: "${{ inputs.channel-id }}"
          text: "${{ env.MESSAGE_TEXT }}"
          ${{ github.run_attempt > 1 && format('thread_ts: "{0}"', env.SLACK_THREAD_ID) || '' }}
          attachments:
            - pretext: "See the details below for a summary of which job(s) ${{ env.MESSAGE_VERB }}."
              color: "${{ env.MESSAGE_COLOR }}"
              fields:
                - title: Build/Publish Image
                  short: true
                  value: "${{ inputs.build-result }}"
                - title: Build/Publish Manifests
                  short: true
                  value: "${{ inputs.publish-manifests-result }}"
              actions:
                - type: button
                  text: Go to workflow run
                  url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}"

    - name: Save Slack Thread ID to File
      if: ${{ env.SLACK_THREAD_ID == 'none' }}
      env:
        SLACK_THREAD_ID: ${{ steps.send-notification.outputs.ts }}
      shell: bash
      run: |
        echo "$SLACK_THREAD_ID" > slack-thread-id

    - name: Store Slack Thread ID as Artifact
      if: ${{ env.SLACK_THREAD_ID == 'none' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: slack-thread-id-${{ github.run_id }}
        path: slack-thread-id
