---
name: Send Notification via Slack
description: "This action sends notifications for different types of workflows"
inputs:
  channel-id:
    description: The channel to sent the message to
  type:
    description: |
      The type of notification to send. Supported types are `container-image-build`
      and `integration-test`.
  build-result:
    description: The result of the build job
  publish-manifests-result:
    description: The result of the publish manifests job
  test-result:
    description: The result of an integration test
  test-health:
    description: The health of the past few integration tests
  failed-tests:
    description: The list (plain text) of failed tests
  slack-token:
    description: The Slack token
runs:
  using: composite
  steps:
    - name: Validate Inputs
      env:
        NOTIFICATION_TYPE: ${{ inputs.type }}

        PUBLISH_MANIFESTS_RESULT: ${{ inputs.publish-manifests-result }}
        BUILD_RESULT: ${{ inputs.build-result }}

        FAILED_TESTS: ${{ inputs.failed-tests }}
        TEST_RESULT: ${{ inputs.test-result }}
        TEST_HEALTH: ${{ inputs.test-health }}
      shell: bash
      run: |
        if [ -z "${NOTIFICATION_TYPE:-}" ]; then
          echo "The type input must be provided"
          exit 1
        fi

        if [ "$NOTIFICATION_TYPE" == "container-image-build" ]; then
          [ -z "${PUBLISH_MANIFESTS_RESULT:-}" ] && echo "The publish-manifests-result input must be provided" && exit 1
          [ -z "${BUILD_RESULT:-}" ] && echo "The build-result input must be provided" && exit 1

          echo "PUBLISH_MANIFESTS_RESULT=$PUBLISH_MANIFESTS_RESULT" | tee -a "$GITHUB_ENV"
          echo "BUILD_RESULT=$BUILD_RESULT" | tee -a "$GITHUB_ENV"
        elif [ "$NOTIFICATION_TYPE" == "integration-test" ]; then
          [ -z "${TEST_RESULT:-}" ] && echo "The test-result input must be provided" && exit 1
          [ -z "${TEST_HEALTH:-}" ] && echo "The test-health input must be provided" && exit 1

          echo "FAILED_TESTS=${FAILED_TESTS:-No failed tests}" | tee -a "$GITHUB_ENV"
          echo "TEST_RESULT=$TEST_RESULT" | tee -a "$GITHUB_ENV"
          echo "TEST_HEALTH=$TEST_HEALTH" | tee -a "$GITHUB_ENV"
        else
          echo "Supported notification types are: 'container-image-build' and 'integration-test'"
          exit 1
        fi

        echo "NOTIFICATION_TYPE=$NOTIFICATION_TYPE" | tee -a "$GITHUB_ENV"

    - name: Retrieve Slack Thread ID
      id: retrieve-slack-thread-id
      continue-on-error: true
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: slack-thread-id-${{ github.run_id }}

    - name: Extract Slack Thread ID into Environment Variable
      if: steps.retrieve-slack-thread-id.outcome == 'success'
      shell: bash
      run: |
        echo "SLACK_THREAD_ID=$(cat slack-thread-id)" | tee -a "$GITHUB_ENV"

    - name: Provide message template variables
      env:
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        SLACK_THREAD_YAML: |
          ${{ steps.retrieve-slack-thread-id.outcome == 'success' && format('thread_ts: "{0}"', env.SLACK_THREAD_ID) || '' }}
        CHANNEL_ID: ${{ inputs.channel-id }}
      shell: bash
      run: |
        export WORKFLOW_RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${GITHUB_RUN_ATTEMPT}"

        if [ "$NOTIFICATION_TYPE" == "container-image-build" ]; then
          # TODO (@Techassi): Also add success template
          if [ "$PUBLISH_MANIFESTS_RESULT" = "failure" ] || [ "$BUILD_RESULT" = "failure" ]; then
            export MESSAGE_VERB=failed
            export MESSAGE_COLOR=aa0000
          else
            export MESSAGE_VERB=succeeded
            export MESSAGE_COLOR=10c400
          fi

          export MESSAGE_TEXT="*$GITHUB_WORKFLOW* $MESSAGE_VERB (attempt $GITHUB_RUN_ATTEMPT)"
          PAYLOAD=$(envsubst < "${GITHUB_ACTION_PATH}/templates/container-image-build/failure.tpl")
          echo -e "PAYLOAD<<EOF\n$PAYLOAD\nEOF" | tee -a "$GITHUB_ENV"
        elif [ "$NOTIFICATION_TYPE" == "integration-test" ]; then
          export HEALTH_SLACK_EMOJI=$(echo "$TEST_HEALTH" | cut -d ',' -f 1)
          export HEALTH_RATE=$(echo "$TEST_HEALTH" | cut -d ',' -f 3)

          if [ "$TEST_RESULT" == "failure" ]; then
            export MESSAGE_TEXT="The integration test for *`$GITHUB_REPOSITORY`* failed."
            PAYLOAD=$(envsubst < "${GITHUB_ACTION_PATH}/templates/integration-test/failure.tpl")
            echo -e "PAYLOAD<<EOF\n$PAYLOAD\nEOF" | tee -a "$GITHUB_ENV"
          else
            export MESSAGE_TEXT="The integration test for *`$GITHUB_REPOSITORY`* succeeded."
            PAYLOAD=$(envsubst < "${GITHUB_ACTION_PATH}/templates/integration-test/success.tpl")
            echo -e "PAYLOAD<<EOF\n$PAYLOAD\nEOF" | tee -a "$GITHUB_ENV"
          fi
        fi

    - name: Send Notification
      id: send-notification
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # 2.1.1
      with:
        method: chat.postMessage
        token: ${{ inputs.slack-token }}
        payload: ${{ env.PAYLOAD }}
        payload-templated: false

    - name: Save Slack Thread ID to File
      if: steps.retrieve-slack-thread-id.outcome == 'failure'
      env:
        SLACK_THREAD_ID_OUTPUT: ${{ steps.send-notification.outputs.ts }}
      shell: bash
      run: |
        echo "$SLACK_THREAD_ID_OUTPUT" > slack-thread-id

    - name: Store Slack Thread ID as Artifact
      if: steps.retrieve-slack-thread-id.outcome == 'failure'
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: slack-thread-id-${{ github.run_id }}
        path: slack-thread-id
