[metadata]
documentation = "https://docs.stackable.tech/home/stable/"
source = "https://github.com/stackabletech/actions/"
authors = "Stackable GmbH <info@stackable.tech>"
vendor = "Stackable GmbH"
licenses = "Apache-2.0"

[build-arguments]
