#!/usr/bin/env bash

set -euo pipefail

AUTO_GENERATED_COMMENT="autogenerated by .scripts/local/update_allowed_scopes.sh"
LIST_TMP=$(mktemp)

echo "# start:scopes: $AUTO_GENERATED_COMMENT" >> "$LIST_TMP"
echo "allowed_scopes = [" >> "$LIST_TMP"

for ACTION in $(find . -mindepth 2 -name action.yaml -print0 | xargs -0 -n 1 dirname | xargs -n 1 basename | sort); do
  echo "  \"$ACTION\"," >> "$LIST_TMP"
done

echo "]" >> "$LIST_TMP"
echo -n "# end:scopes" >> "$LIST_TMP"

LIST_CONTENT=$(sed ':a;N;$!ba;s/\n/\\n/g' "$LIST_TMP")
SCOPES_TMP=$(mktemp)

awk -v LIST_CONTENT="$LIST_CONTENT" "/^# start:scopes/{flag=1; print LIST_CONTENT} {if(!flag)print} /# end:scopes/{flag=0;next}" committed.toml > "$SCOPES_TMP"
cp "$SCOPES_TMP" committed.toml

rm "$LIST_TMP" "$SCOPES_TMP"
