#!/usr/bin/env bash

set -euo pipefail

AUTO_GENERATED_COMMENT="autogenerated by $0"
LIST_TMP=$(mktemp)

echo "<!-- start:links: $AUTO_GENERATED_COMMENT -->" >> "$LIST_TMP"

for ACTION in $(find . -mindepth 2 -name action.yaml -print0 | xargs -0 -n 1 dirname | xargs -n 1 basename | sort); do
  echo "- [$ACTION](./${ACTION}/README.md)" >> "$LIST_TMP"
done

echo -n "<!-- end:links -->" >> "$LIST_TMP"

LIST_CONTENT=$(sed ':a;N;$!ba;s/\n/\\n/g' "$LIST_TMP")
README_TMP=$(mktemp)

awk "/^<!-- start:links/{flag=1; print \"$LIST_CONTENT\"} {if(!flag)print} /<!-- end:links/{flag=0;next}" README.md > "$README_TMP"
cp "$README_TMP" README.md

rm "$LIST_TMP" "$README_TMP"
