---
name: Setup Stackable Tools
description: This action sets up Stackable tools
inputs:
  boil-version:
    description: The version of boil
  stackablectl-version:
    description: The version of stackablectl
  interu-version:
    description: The version of interu
  beku-version:
    description: The version of beku
runs:
  using: composite
  steps:
    - name: Install boil
      if: inputs.boil-version
      env:
        BOIL_VERSION: ${{ inputs.boil-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        ARCH=$(uname -m)

        if [ "$BOIL_VERSION" == "latest" ]; then
          curl -fsSL -o /tmp/boil "https://github.com/stackabletech/docker-images/releases/latest/download/boil-${ARCH}-unknown-linux-gnu"
        else
          curl -fsSL -o /tmp/boil "https://github.com/stackabletech/docker-images/releases/download/boil-${BOIL_VERSION}/boil-${ARCH}-unknown-linux-gnu"
        fi

        sudo install -m 755 -t /usr/local/bin /tmp/boil

    - name: Install stackablectl
      if: inputs.stackablectl-version
      env:
        STACKABLECTL_VERSION: ${{ inputs.stackablectl-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        ARCH=$(uname -m)

        if [ "$STACKABLECTL_VERSION" == "latest" ]; then
          curl -fsSL -o /tmp/stackablectl "https://github.com/stackabletech/stackable-cockpit/releases/latest/download/stackablectl-${ARCH}-unknown-linux-gnu"
        else
          curl -fsSL -o /tmp/stackablectl "https://github.com/stackabletech/stackable-cockpit/releases/download/stackablectl-${STACKABLECTL_VERSION}/stackablectl-${ARCH}-unknown-linux-gnu"
        fi

        sudo install -m 755 -t /usr/local/bin /tmp/stackablectl

    - name: Install interu
      if: inputs.interu-version
      env:
        INTERU_VERSION: ${{ inputs.interu-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        ARCH=$(uname -m)

        if [ "$INTERU_VERSION" == "latest" ]; then
          curl -fsSL -o /tmp/interu "https://github.com/stackabletech/actions/releases/latest/download/interu-${ARCH}-unknown-linux-gnu"
        else
          curl -fsSL -o /tmp/interu "https://github.com/stackabletech/actions/releases/download/interu-${INTERU_VERSION}/interu-${ARCH}-unknown-linux-gnu"
        fi

        sudo install -m 755 -t /usr/local/bin /tmp/interu

    - name: Install beku
      if: inputs.beku-version
      env:
        BEKU_VERSION: ${{ inputs.beku-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        pip install "beku-stackabletech==$BEKU_VERSION"
