---
name: Setup Stackable Tools
description: This action sets up Stackable tools
inputs:
  boil-version:
    description: The version of boil
  stackablectl-version:
    description: The version of stackablectl
  interu-version:
    description: The version of interu
  beku-version:
    description: The version of beku
runs:
  using: composite
  steps:
    - name: Install boil
      if: inputs.boil-version
      env:
        BOIL_VERSION: ${{ inputs.boil-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_boil.sh"

    - name: Install stackablectl
      if: inputs.stackablectl-version
      env:
        STACKABLECTL_VERSION: ${{ inputs.stackablectl-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_stackablectl.sh"

    - name: Install interu
      if: inputs.interu-version
      env:
        INTERU_VERSION: ${{ inputs.interu-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: "$GITHUB_ACTION_PATH/../.scripts/actions/install_interu.sh"

    - name: Install beku
      if: inputs.beku-version
      env:
        BEKU_VERSION: ${{ inputs.beku-version }}
        GITHUB_DEBUG: ${{ runner.debug }}
      shell: bash
      run: |
        set -euo pipefail
        [ -n "$GITHUB_DEBUG" ] && set -x

        pip install "beku-stackabletech==$BEKU_VERSION"
