---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8sattributes-processor-container-log-scrape
roleRef:
  kind: ClusterRole
  name: k8sattributes-processor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: container-log-scrape
  namespace: opentelemetry-operator
