---
name: Build interu

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      target:
        required: true
        type: string
      upload:
        default: false
        type: boolean

env:
  RUST_VERSION: 1.83.0

jobs:
  build:
    name: Build interu-${{ inputs.target }}
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Rust Toolchain
        env:
          RUST_TARGETS: ${{ inputs.target }}
        shell: bash
        # NOTE: target is a comma separated list of targets, which is fine here
        # but further down it would break. Maybe we want to validate the target
        # input is actually one target (and use the matrix for building multiple
        # targets in parallel)
        run: rustup toolchain install "${RUST_VERSION}" --target "${RUST_TARGETS}"

      - name: Build Binary
        env:
          TARGET: ${{ inputs.target }}
        run: cargo build --target "$TARGET" --release --package interu

      - name: Rename Binary
        env:
          TARGET: ${{ inputs.target }}
        run: mv "target/$TARGET/release/interu" "interu-$TARGET"

      - name: Upload Artifact
        if: inputs.upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: interu-${{ inputs.target }}
