---
name: actions-smoke-test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/pr_actions-smoke-test.yml
      - build-container-image/action.yaml
      - build-product-image/action.yaml
      - free-disk-space/action.yaml
      - publish-image/action.yaml
      - publish-index-manifest/action.yaml
      - send-slack-notification/action.yaml
      - shard/action.yaml
      - smoke/*

jobs:
  generate_matrix:
    name: Generate Version List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - id: shard
        uses: ./shard
        with:
          product-name: smoke
          config-file: smoke/conf.py
    outputs:
      versions: ${{ steps.shard.outputs.versions }}

  build:
    name: Build/Publish Smoke Test (${{ matrix.versions }}-${{ matrix.runner.arch }}) Image
    needs: [generate_matrix]
    permissions:
      id-token: write
    runs-on: ${{ matrix.runner.name }}
    strategy:
      matrix:
        runner:
          - {name: "ubuntu-latest", arch: "amd64"}
          - {name: "ubicloud-standard-8-arm", arch: "arm64"}
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Free Disk Space
        uses: ./free-disk-space

      - name: Build Product Container Image
        id: build
        uses: ./build-product-image
        with:
          product-name: smoke
          product-version: ${{ matrix.versions }}
          bake-config-file: smoke/conf.py
          extra-tag-data: pr-321

      - name: Publish Container Image on oci.stackable.tech
        uses: ./publish-image
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$stackable+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
          image-repository: stackable/smoke
          image-manifest-tag: ${{ steps.build.outputs.image-manifest-tag }}
          source-image-uri: localhost/smoke:${{ steps.build.outputs.image-manifest-tag }}

  publish_manifests:
    name: Build/Publish ${{ matrix.versions }} Index Manifest
    needs: [generate_matrix, build]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Publish and Sign Image Index Manifest to oci.stackable.tech
        uses: ./publish-index-manifest
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$stackable+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_STACKABLE_GITHUB_ACTION_BUILD_SECRET }}
          image-repository: stackable/smoke
          image-index-manifest-tag: ${{ matrix.versions }}-stackable0.0.0-dev

  notify:
    name: Failure Notification
    needs: [generate_matrix, build, publish_manifests]
    runs-on: ubuntu-latest
    if: failure() || github.run_attempt > 1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Send Notification
        uses: ./send-slack-notification
        with:
          publish-manifests-result: ${{ needs.publish_manifests.result }}
          build-result: ${{ needs.build.result }}
          slack-token: ${{ secrets.SLACK_CONTAINER_IMAGE_TOKEN }}
          channel-id: C07UG6JH44F # notifications-container-images
